name: task_flow_pro
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  get_it: ^9.2.0
  intl: ^0.20.2
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  freezed: ^3.2.3

flutter:
  uses-material-design: true
